# Numpy Learning 

In [1]:
import numpy as np

In [2]:
myarr = np.array([3,1,2,4,5],np.int8)

In [3]:
myarr

array([3, 1, 2, 4, 5], dtype=int8)

In [4]:
myar = np.array([[3,1,2,4,5]],np.int8)

In [5]:
myar[0,2]

2

In [6]:
myarr.shape

(5,)

In [7]:
myar.shape

(1, 5)

In [8]:
myarr.dtype

dtype('int8')

In [9]:
myar[0,2] = 99

In [10]:
myar

array([[ 3,  1, 99,  4,  5]], dtype=int8)

*** There are 5 ways of creating arrays in numpy ***
1. conversion from other python structures
2. Intrinsic numpy array creation objects(e.g. arragne ones, zeros etc)
3. Reading array from disk, either from standard or custom formats
4. Creating arrays from raw bytes through the use of strings or buffers
5. Use of special library functions(e.g random)

# conversion from other python structures

In [11]:
listarray = np.array([[1,2,3],[4,5,6],[6,7,8]])

In [12]:
listarray.shape

(3, 3)

In [13]:
listarray.dtype

dtype('int64')

In [14]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [15]:
listarray.size

9

In [16]:
np.array({44,66,77}) # this is not efficient

array({66, 44, 77}, dtype=object)

In [17]:
zeros = np.zeros((2,5))

In [18]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
zeros.shape

(2, 5)

In [20]:
zeros.dtype

dtype('float64')

In [21]:
rng = np.arange(15)

In [22]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
lspace = np.linspace(1,4,10)

In [24]:
lspace

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [25]:
emp = np.empty((4,6))

In [26]:
emp

array([[ 2.00000000e+000, -2.68679001e+154,  9.38724727e-323,
         0.00000000e+000,  0.00000000e+000,  1.15998412e-028],
       [ 2.44171989e+232,  8.00801729e+159,  3.48990054e-086,
         6.01347002e-154,  4.66726139e-062,  3.44357013e-086],
       [ 9.96009977e-043,  6.01347033e-154,  3.64464637e-086,
         4.66726146e-062,  6.01347002e-154,  1.51979058e-047],
       [ 3.84572312e-086,  6.01347002e-154,  4.66726139e-062,
         3.84572307e-086,  9.96009977e-043,  6.01347033e-154]])

In [27]:
emp_lk = np.empty_like(lspace) # copies the size and makes an empty array

In [28]:
emp_lk

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [29]:
ide = np.identity(10) # identity matrix of size 10 x 10

In [30]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [31]:
ide.shape

(10, 10)